allow to configure the saleschannel in the product export command
FACT-Finder-Web-Components/shopware6-plugin pull request #13
Opened 2021-03-12 15:17 UTC by breaker92

Currently if the shop has more then one saleschannel, you can not choose the saleschannel for which you want to export.

2021-03-12 15:44 UTC, breaker92 commented
Please consider to increase the CouplingBetweenObjects in phpmd:
Otherwise this issue won't be solved!

2021-03-16 05:55 UTC, a-laurowski commented
> Please consider to increase the CouplingBetweenObjects in phpmd:
> Otherwise this issue won't be solved!

2021-03-19 08:05 UTC, breaker92 commented
@a-laurowski done

2021-03-19 08:10 UTC, a-laurowski requested changes

2021-03-19 09:39 UTC, a-laurowski commented
> @a-laurowski done

@breaker92  Have you push something?

2021-03-24 08:28 UTC, breaker92 commented on src/Command/ProductExportCommand.php
> +        if ($input->hasOption(self::SALESCHANNEL_OPTION)) {
Hi @a-laurowski I've changed it to argument

2021-03-25 08:04 UTC, a-laurowski commented
Hi @breaker92  
Thanks for the update! Looks good, only the one thing from code sniffer to fix.
Could you squash the commits into a single one? I could do this via GitHub but i'm afraid that in that case i will stole an authorship of that change which i obviously don't want to.

2021-03-26 08:09 UTC, breaker92 commented
> Hi @breaker92
> Thanks for the update! Looks good, only the one thing from code sniffer to fix.
> Could you squash the commits into a single one? I could do this via GitHub but i'm afraid that in that case i will stole an authorship of that change which i obviously don't want to.

Hi @a-laurowski 
the code sniffer issue is solved and the commits are squashed.

2021-03-26 08:23 UTC, a-laurowski approved these changes

2021-03-26 08:24 UTC, a-laurowski commented
> > Hi @breaker92
> > Thanks for the update! Looks good, only the one thing from code sniffer to fix.
> > Could you squash the commits into a single one? I could do this via GitHub but i'm afraid that in that case i will stole an authorship of that change which i obviously don't want to.
> 
> Hi @a-laurowski
> the code sniffer issue is solved and the commits are squashed.

@breaker92  thanks, i'm merging the PR

2021-03-26 08:25 UTC, merged